---@diagnostic disable: missing-return

---sm.regui, ReDoing Graphical User Interfaces
sm.regui = {}

---Creates a GUI from a layout file
---@param path string The path to the layout file
---@return ReGui.GuiInterface The created GUI object
function sm.regui.createGuiFromLayout(path) end

---Creates an empty GUI
---@return ReGui.GuiInterface The created GUI object
function sm.regui.createGui() end

--- UTILS --

---A XMLColorful theme. Keys are token names, Values are the color associated to that token.
---@alias ReGui.XMLColorful.Theme table<string, string>

-- Library to add coloring to XML data to be used in a MyGUI text widget.
sm.regui.xmlcolorful = {}

---Gets all theme names
---@return string[] names All themen ames
function sm.regui.xmlcolorful.getThemeNames() end

---Gets all token type names generated by the tokenizer.
---@return string[] tokenTypes All token types
function sm.regui.xmlcolorful.getTokenTypes() end

---Registers or replaces a theme.
---@param name string The name of the new theme
---@param theme ReGui.XMLColorful.Theme The contents of the theme.
function sm.regui.xmlcolorful.addTheme(name, theme) end

---Gets a theme by name.
---@param name string The name of the theme to get
---@return ReGui.XMLColorful.Theme? theme The theme, or nil if not found
function sm.regui.xmlcolorful.getTheme(name) end

---Converts XML text into a color-prefixed string for ReGui rich text rendering.
---@param xml string The XML text to color
---@param theme ReGui.XMLColorful.Theme? The theme to use for coloring
---@return string coloredXML The color-prefixed string
function sm.regui.xmlcolorful.colorXML(xml, theme) end

--- CLASSES ---

---A interface for creating and managing GUIs with sm.regui
---@class ReGui.GuiInterface
local GuiInterface = {}

---Renders the GUIInterface into a valid MyGUI layout file.
---@param prettify boolean? Whether the output should be as small as possible or be readable for the user. Defaults to minimal.
---@return string output The produced output.
function GUIInterface:render(prettify) end

---Opens the GUIInterface.
function GUIInterface:open() end