---@diagnostic disable: missing-return

---sm.regui, ReDoing Graphical User Interfaces
sm.regui = {}

---Creates a GUI from a layout file
---@param path string The path to the layout file
---@return ReGui.GuiInterface The created GUI object
function sm.regui.createGuiFromLayout(path) end

---Creates an empty GUI
---@return ReGui.GuiInterface The created GUI object
function sm.regui.createGui() end

--- UTILS --

---A XMLColorful theme. Keys are token names, Values are the color associated to that token.
---@alias ReGui.XMLColorful.Theme table<string, string>

-- Library to add coloring to XML data to be used in a MyGUI text widget.
sm.regui.xmlcolorful = {}

---Gets all theme names
---@return string[] names All themen ames
function sm.regui.xmlcolorful.getThemeNames() end

---Gets all token type names generated by the tokenizer.
---@return string[] tokenTypes All token types
function sm.regui.xmlcolorful.getTokenTypes() end

---Registers or replaces a theme.
---@param name string The name of the new theme
---@param theme ReGui.XMLColorful.Theme The contents of the theme.
function sm.regui.xmlcolorful.addTheme(name, theme) end

---Gets a theme by name.
---@param name string The name of the theme to get
---@return ReGui.XMLColorful.Theme? theme The theme, or nil if not found
function sm.regui.xmlcolorful.getTheme(name) end

---Converts XML text into a color-prefixed string for ReGui rich text rendering.
---@param xml string The XML text to color
---@param theme ReGui.XMLColorful.Theme? The theme to use for coloring
---@return string coloredXML The color-prefixed string
function sm.regui.xmlcolorful.colorXML(xml, theme) end

--- CLASSES ---

---A interface for creating and managing GUIs with sm.regui
---@class ReGui.GuiInterface
local GuiInterface = {}

---Renders the GUIInterface into a valid MyGUI layout file.
---@param prettify boolean? Whether the output should be as small as possible or be readable for the user. Defaults to minimal.
---@return string output The produced output.
function GuiInterface:render(prettify) end

---Opens the GuiInterface.
function GuiInterface:open() end

---A parsed widget in the GUI tree.
---@class ReGui.Widget
local Widget = {}

---Gets a user-string value by key.
---@param key string The user-string key to read.
---@return string? value The value for the key, or nil if the key does not exist.
function Widget:getUserString(key) end

---Sets a user-string value.
---@param key string The user-string key to write.
---@param value string The value to assign.
function Widget:setUserString(key, value) end

---Gets all user-string keys in this widget.
---@return string[] keys A list of all user-string keys.
function Widget:getAllUserStringKeys() end

---Gets a node-property value by key.
---@param key string The node-property key to read.
---@return string? value The value for the key, or nil if the key does not exist.
function Widget:getNodeProperty(key) end

---Sets a node-property value.
---@param key string The node-property key to write.
---@param value string The value to assign.
function Widget:setNodeProperty(key, value) end

---Gets all node-property keys in this widget.
---@return string[] keys A list of all node-property keys.
function Widget:getAllNodePropertyKeys() end

---Gets a property value by key.
---@param key string The property key to read.
---@return string? value The value for the key, or nil if the key does not exist.
function Widget:getProperty(key) end

---Sets a property value.
---@param key string The property key to write.
---@param value string The value to assign.
function Widget:setProperty(key, value) end

---Gets all property keys in this widget.
---@return string[] keys A list of all property keys.
function Widget:getAllPropertyKeys() end

---Gets the parent widget.
---@return ReGui.Widget? parent The parent widget, or nil if this is a root widget.
function Widget:getParent() end

---Sets the parent widget.
---@param parent ReGui.Widget? parent The new parent widget, or nil to detach this widget.
function Widget:setParent(parent) end

---Gets the GUI interface that owns this widget.
---@return ReGui.GuiInterface? guiInterface The owning GUI interface, or nil if detached.
function Widget:getGUIInterface() end

---Sets the GUI interface for this widget and its subtree.
---@param guiInterface ReGui.GuiInterface? guiInterface The GUI interface to assign, or nil to clear.
function Widget:setGUIInterface(guiInterface) end

---Renders this widget and its children into MyGUI layout XML.
---@param indentationLevel number? The base indentation level used for pretty rendering.
---@param prettify boolean? Whether to render with indentation and line breaks.
---@return string output The rendered XML fragment for this widget subtree.
function Widget:renderWidget(indentationLevel, prettify) end